#!/usr/bin/env python3
"""
Regenerate docs/NUMBERS-TO-CONFIRM.md from the CONFIRM markers in the code.

    python3 tools/confirm-list.py

Every placeholder figure in the project is tagged // CONFIRM or [CONFIRM: ...].
This walks the source and produces the checklist, so the list can never drift
out of step with what's actually in the files. Delete the marker as you replace
each number, re-run this, and watch the list shrink to nothing.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILES = ["assets/js/content.js", "assets/js/pricing.js",
         "backend/apps-script/Config.gs", "backend/apps-script/Nurture.gs"]

BLURB = {
 "assets/js/content.js": ("What visitors read in the house",
   "Everything on the eight station pages. Facts, cost bands, and the honest lines. "
   "These carry Mayflower's name three feet from the thing being described, so a wrong "
   "number here is worse than no number at all."),
 "assets/js/pricing.js": ("The estimator's math",
   "Read this file line by line before anything goes live. These are the figures that "
   "produce the range a prospect gets emailed. The defaults are plausible Park City "
   "numbers, not Mayflower's numbers."),
 "backend/apps-script/Config.gs": ("Backend settings", "Addresses and phone numbers."),
 "backend/apps-script/Nurture.gs": ("Follow-up emails",
   "These only matter on the day each one is drafted, so they are not blockers for "
   "opening weekend. The first two on the Tier A list come due within four days."),
}

def collect():
    out = []
    for rel in FILES:
        path = os.path.join(ROOT, rel)
        rows = []
        for i, line in enumerate(open(path), 1):
            if "CONFIRM" not in line:
                continue
            if line.lstrip().startswith((">>>", "*", "/*")) or "docs/NUMBERS" in line:
                continue
            text = line.strip()
            note = ""
            m = re.search(r"//\s*CONFIRM:?\s*(.*)$", text)
            if m:
                note = m.group(1).strip()
                text = text[:m.start()].strip().rstrip(",")
            m2 = re.search(r"\[CONFIRM:?\s*([^\]]*)\]", text)
            if m2:
                note = m2.group(1).strip()
            rows.append((i, text, note))
        out.append((rel, rows))
    return out

lines = ["# Numbers to confirm",
         "",
         "*Generated by `python3 tools/confirm-list.py`. Do not edit by hand.*",
         "",
         "Every figure below is a placeholder. They are realistic for a Park City custom",
         "home at this level, and none of them are Mayflower's actual numbers.",
         "",
         "**Nothing goes in front of a visitor until this list is empty or the line has been",
         "deleted on purpose.** Replace the value, delete the `CONFIRM` marker, re-run the",
         "script, and the entry disappears.",
         ""]

data = collect()
total = sum(len(r) for _, r in data)
lines += ["**%d open items.**" % total, ""]

for rel, rows in data:
    title, blurb = BLURB[rel]
    lines += ["---", "", "## %s" % title, "`%s` — %d item%s" % (rel, len(rows), "" if len(rows) == 1 else "s"),
              "", blurb, ""]
    for i, text, note in rows:
        short = text if len(text) < 150 else text[:147] + "..."
        lines.append("- **L%d** — %s" % (i, note if note else "confirm this figure"))
        lines.append("  ```")
        lines.append("  " + short)
        lines.append("  ```")
    lines.append("")

out = os.path.join(ROOT, "docs", "NUMBERS-TO-CONFIRM.md")
os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, "w").write("\n".join(lines) + "\n")
print("docs/NUMBERS-TO-CONFIRM.md — %d open items" % total)
